name = "restaurant-den-anker-dashboard-handmatig"
main = "worker.js"
compatibility_date = "2026-06-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "TOKENS"
id = "76629a1c5dcb4545bc2dde3f0fdff3d6"
